### ISSUE TITLE
alpakatest and alpaka fail to build

### ISSUE THREAD

**Issue by makortel** [cms-patatrack/pixeltrack-standalone#126]
From https://github.com/cms-patatrack/pixeltrack-standalone/pull/120#issuecomment-724907150

> The `alpaka` and `alpakatest` fail to build with
> ```
> .../pixeltrack-standalone/external/alpaka/include/alpaka/core/Concepts.hpp:81:33: error: '__T0' was not declared in this scope
>                  static_assert(std::is_base_of<type, TDerived>::value, "The type implementing the concept has to be a publicly accessible base class!");
>                                  ^~~~
> .../pixeltrack-standalone/external/alpaka/include/alpaka/core/Concepts.hpp:81:33: note: suggested alternative: '__y0'
>                  static_assert(std::is_base_of<type, TDerived>::value, "The type implementing the concept has to be a publicly accessible base class!");
>                                  ^~~~
>                                  __y0
> .../pixeltrack-standalone/external/alpaka/include/alpaka/core/Concepts.hpp:81:47: error: template argument 1 is invalid
>                  static_assert(std::is_base_of<type, TDerived>::value, "The type implementing the concept has to be a publicly accessible base class!");
> ```
> 
> Updating Alpaka to 0.5.0 changed the error to
> ```
> .../pixeltrack-standalone/external/alpaka/include/alpaka/core/UniformCudaHip.hpp: In instantiation of 'void alpaka::uniform_cuda_hip::detail::rtCheckIgnore(const Error_t&, const char*, const char*, const int&, TErrors&& ...) [with TErrors = {cudaError}; alpaka
> ::uniform_cuda_hip::detail::Error_t = cudaError]':
> .../pixeltrack-standalone/external/alpaka/include/alpaka/queue/cuda_hip/QueueUniformCudaHipRtBase.hpp:196:342:   required from here
> .../pixeltrack-standalone/external/alpaka/include/alpaka/core/UniformCudaHip.hpp:86:61: error: missing braces around initializer for 'std::__array_traits<cudaError, 1>::_Type' {aka 'cudaError [1]'} [-Werror=missing-braces]
>                      std::array<Error_t, sizeof...(ignoredErrorCodes)> const aIgnoredErrorCodes{ignoredErrorCodes...};
>                                                              ^~~~~~~~~~~~~~~~~~
> ```
> which can be worked around.

**Comment by ghugo83** [comment]
Yes with Cuda 11.1, I still get an issue with cudauvm, but alpaka and alpakatest build was working on my local.
These were just few changes to do in the Makefile (sorry here in temporary, debug style, also including change to Maxwell as in my local): https://github.com/ghugo83/pixeltrack-standalone/commit/769d8cc38f457f15251236f2a02b48c1f2914bf5

**Comment by makortel** [comment]
Should we include more proper support for Maxwell then?

(from your Makefile changes setting `export CUDA_ARCH := 35 50 60 70` and adding
```
else ifeq ($(KOKKOS_CUDA_ARCH),50)
  KOKKOS_CMAKE_CUDA_ARCH := -DKokkos_ARCH_MAXWELL50=On
```
should be sufficient)

**Comment by ghugo83** [comment]
With cudauvm I still get this issue though (but was already there with CUDA 10.2):
Found 1 devices
terminate called after throwing an instance of 'std::runtime_error'
```
  what():  
/home/ghugo/CMSSW/Portability/pixeltrack-standalone/src/cudauvm/CondFormats/SiPixelFedCablingMapGPUWrapper.cc, line 32:
cudaCheck(cudaMemPrefetchAsync(cablingMap_, sizeof(SiPixelFedCablingMapGPU), device, stream.get()));
cudaErrorInvalidDevice: invalid device ordinal
Aborted (core dumped)
```

**Comment by ghugo83** [comment]
>Should we include more proper support for Maxwell then?
Ok yes will just add that

**Comment by makortel** [comment]
> With cudauvm I still get this issue though (but was already there with CUDA 10.2):
> Found 1 devices
> terminate called after throwing an instance of 'std::runtime_error'
> 
> ```
>   what():  
> /home/ghugo/CMSSW/Portability/pixeltrack-standalone/src/cudauvm/CondFormats/SiPixelFedCablingMapGPUWrapper.cc, line 32:
> cudaCheck(cudaMemPrefetchAsync(cablingMap_, sizeof(SiPixelFedCablingMapGPU), device, stream.get()));
> cudaErrorInvalidDevice: invalid device ordinal
> Aborted (core dumped)
> ```

Interesting. Could this be specific to Maxwell? I have tested `cudauvm` in Volta and Turing.
