### ISSUE TITLE
Replace `wget` with `curl` in the Makefile ?

### ISSUE THREAD

**Issue by fwyzard** [cms-patatrack/pixeltrack-standalone#173]
`curl` supports SOCKS5 proxies (useful when working on a private network, with no external connectivity except via an SSH tunnel) which makes it handy on the GPU machines at P5.

However, `wget` might still be more widespread.

Maybe try something like "if curl is available, use `curl -L -s -S`, else use `wget -nv -O -` ?

**Comment by makortel** [comment]
https://github.com/cms-patatrack/pixeltrack-standalone/pull/176 replaced all uses `wget` with `curl` (so the question of the issue has been addressed). I'd leave question of using `wget` if `curl` is not available to the time when we encounter such a system.
