### ISSUE TITLE
[alpaka] porting of warp-level instructions not possible 

### ISSUE THREAD

**Issue by felicepantaleo** [cms-patatrack/pixeltrack-standalone#20]
it is not possible to directly port to alpaka:
- `__shfl_up_sync`: https://github.com/cms-patatrack/pixeltrack-standalone/blob/96d61f24dbaf704f3a7d533491aee4af00f8b328/src/cuda/CUDACore/prefixScan.h#L17
- `__ballot_sync`: https://github.com/cms-patatrack/pixeltrack-standalone/blob/96d61f24dbaf704f3a7d533491aee4af00f8b328/src/cuda/CUDACore/prefixScan.h#L56

See issues in alpaka:

https://github.com/alpaka-group/alpaka/issues/18
https://github.com/alpaka-group/alpaka/issues/15

**Comment by j-stephan** [comment]
FYI, `__ballot_sync` has had an alpaka equivalent since July 2020. See [here](https://github.com/alpaka-group/alpaka/blob/develop/include/alpaka/warp/Traits.hpp) for reference. We are targeting the `__shfl`s for the next release.

**Comment by makortel** [comment]
Thanks @j-stephan for the update!

**Comment by fwyzard** [comment]
These have been added in Alpaka 0.6.0 and 0.7.0 .
