### ISSUE TITLE
Compiler version check fails on Ubuntu

### ISSUE THREAD

**Issue by markdewing** [cms-patatrack/pixeltrack-standalone#283]
The compiler version check added in #280 fails on Ubuntu.
Symptoms
```
/bin/sh: 1: 903: not found
Makefile: 19: *** This program requires GCC 8.0 or later, but the current compiler is GCC 9.3.  Stop.
```
The makefile `shell` command for the comparison calls out to the default shell.  On Ubuntu, that is dash.  The comparison uses a bash extension.

Workarounds:
1. `Use SHELL=/bin/bash` in the Makefile
2. Use `test` rather than `(( ))` in the comparison

**Comment by fwyzard** [comment]
@markdewing thank you for reporting this.

Can you check that #284 fixes the issue for you ?

**Comment by markdewing** [comment]
Yes, #284 fixes the issue on my machine.

**Comment by fwyzard** [comment]
:+1:
