### ISSUE TITLE
TBB removed tbb::task

### ISSUE THREAD

**Issue by markdewing** [cms-patatrack/pixeltrack-standalone#295]
`tbb::task` was deprecated and has been removed from oneAPI distribution (eg 2021.3)
The downloaded version of TBB (2020 update 3) still has it.

The `env.sh` script will initialize oneAPI if it is present on the system (`source /opt/intel/oneapi/setvar.sh`).  The build will pick up that version of TBB rather than the downloaded version (I'm not sure how - the oneapi path is not present in the command lines printed out during the makefile run.  Probably through the `CPATH` environment variable.)

The issue shows up when trying to build the serial version (and other versions) with the error
```
                 from /home/mdewing/physics/hep/tracking/patatrack/pixeltrack/pixeltrack-standalone/src/serial/bin/EventProcessor.cc:1:
/home/mdewing/physics/hep/tracking/patatrack/pixeltrack/pixeltrack-standalone/src/serial/Framework/WaitingTask.h:37:44: error: expected class-name before ‘{’ token
   37 |   class WaitingTask : public tbb::task {
      |                                            ^
...
```
A workaround is to remove the oneapi set up line in `env.sh`

What is the longer term plan for dealing with this?  Move to `task_group`?

**Comment by makortel** [comment]
Sounds like the time has come to update the codebase for `tbb::task_group` following what was done in CMSSW, and also update the TBB version to something recent. I'll get to it.

**Comment by makortel** [comment]
#305 migrates the direct use of `tbb::task` to `tbb::task_group`
